[project]
name = "csv-audit-ahmed"
version = "0.1.0"
description = "A simple CSV audit tool"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
csv-audit = "main:main"
